name: Zip Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create zip archive
      shell: bash
      env:
        ORG_NAME: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        ZIP_NAME: ${{ github.repository_owner }}-${{ github.event.repository.name }}.zip
      run: |
        echo "Organization Name: $ORG_NAME"
        echo "Repository Name: $REPO_NAME"
        echo "Zip File Name: $ZIP_NAME"

        # Exclude .py files and other specified patterns
        zip -r "$ZIP_NAME" ./* -x "*.py" -x "path/to/exclude/*" -x "*.md"

    - name: Upload zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ env.ZIP_NAME }}